### ISSUE TITLE
Slow disk operations

### ISSUE THREAD

**Issue by DOFfactory** [djaydev/docker-krusader#1]
I wonder whether there is any chance of making operations like copy or move files in a 'native' speeds? The operations within on a same partition is taking a considerable time while it runs through the docker. Any advice is welcome.

**Comment by djaydev** [comment]
I did some tests after your post on my system with Krusader.  One file copy on a harddrive and another file copy on a SSD and I'm getting my normal speed I get from the linux machine itself.  My machine running Krusader is a Intel 8700K Unraid operating system.

**Comment by DOFfactory** [comment]
Hi @djaydev, thanks for the test. I must admit I use it over the WAN through VNC. When I move a file, it is slower than the 'native' web frontend of the NAS. When I move eg. a 4GB file, it shows the progress bar for 30s or so... a native NAS frontend doesn't, and it is quicker. Does it make any change if the docker is run as `bridge` or `host` connection? No idea what might slow things down, maybe the VNC?

**Comment by djaydev** [comment]
Is your NAS a pre-built device such as a synology?
If so, I don't have a lot of experience with those devices, but for my server running Krusader I use bridge network connection.  
The VNC shouldn't slow down the file copy, unless the CPU resources of the device are being utilized heavily by the VNC during the file copy.

**Comment by DOFfactory** [comment]
Yes, I use ADM from Asustor. By accident I found a solution. Instead of a normal user with its PUID and GUID, if I use the admin's PUID and GUID I get full speed in moving/copying. Strange...
