### ISSUE TITLE
Set screen resolution

### ISSUE THREAD

**Issue by mechrekt** [djaydev/docker-krusader#2]
Hi, I'm trying to set the env variables to have a bigger resolution in VNC but DISPLAY_WIDTH and DISPLAY_HEIGHT seems not to have effect in this docker. Thank you.

**Comment by djaydev** [comment]
Hi.  Here's my current height/width settings below.  I changed it to 1280x768 to test, and the krusader window inside the VNC became much smaller.  I then changed it back to my original settings 1920x1080 and it grew in size again.  I'm not sure how else to help, those settings are carried from the base image.

my docker variables for height/width:

-e 'DISPLAY_WIDTH'='1920' -e 'DISPLAY_HEIGHT'='1080'

**Comment by mechrekt** [comment]
That worked! Thank you!
