### ISSUE TITLE
SMB

### ISSUE THREAD

**Issue by mechrekt** [djaydev/docker-krusader#3]
In "New Network Connection" I only see ftp or webdav. SMB seems not to be present.
I don't know if it's really an issue or just a lack of funtionality. Thank you

**Comment by djaydev** [comment]
added more protocols to new network connection in latest update

**Comment by mechrekt** [comment]
Sorry I've djaydev/krusader:latest and just restarted the docker, but I dont see that.
Thank you for your great work!

**Comment by djaydev** [comment]
cant just restart, have to update

**Comment by mechrekt** [comment]
Sorry this was my fault, i'm noob with docker. I had to deploy again in portainer. Now it works great! Thank you again!
