### ISSUE TITLE
kdeglobals / environment - changing date format?

### ISSUE THREAD

**Issue by techie2000** [djaydev/docker-krusader#4]
I was under the impression that adding a kdeglobals file to the persisted data store /xdg/config/ location should allow me to change the date format displayed in the panes? (reference [https://itectec.com/ubuntu/ubuntu-date-time-format-in-krusader-is-it-changeable-at-all-duplicate/](https://itectec.com/ubuntu/ubuntu-date-time-format-in-krusader-is-it-changeable-at-all-duplicate/) )

I created a file with below content, restarted, but saw no changes, intended or otherwise.
```
[Locale]
Country=gb
DateFormatShort=%Y-%m-%d
Language=en_GB
TimeFormat=%H:%M:%S
```

I also saw the below in the container `/etc/xdg/openbox/environment`file
```
# Set system-wide environment variables here for Openbox
# User-specific variables should be placed in $HOME/.config/openbox/environment
#

# To set your language for displaying messages and time/date formats, use the following:
#LANG=en_CA.UTF8

# To set your keyboard layout, you need to modify your X config:
# http://www.google.com/search?q=how+to+set+keyboard+layout+xorg
```
so I created that file with `LANG=en_GB.UTF8` in the hope of at least getting UK rather than US date formats, and restarted the container, but again saw no differences.

Is it just not possible to change the gui date formats when running in a container?

**Comment by djaydev** [comment]
I've never tried but I assume you should be able to do it.  We just have to find the location krusader looks for the config file for date format, and possible the file's name and parameters needed in said file.

From that link you sent @itectec they mentioned `~/.kde/share/config/kdeglobals` I would start there. Krusader uses `~/` as the mapped volume /config. So in the /config on the host I would create a folder `.kde/share/config` not sure if that would work but its a start.

Just to be clear, I really don't have any clue how to tell Krusader to use a different date format.  I just package the app up in a container image, the customization of the app is on the app itself.

**Comment by techie2000** [comment]
FYI I've not had any luck getting this to work. I've even tried resorting to setting a locale inside the container, but with no joy.

**Comment by djaydev** [comment]
I tested on my machine as well without success.
I tried the path from the link you sent `~/.kde/share/config/kdeglobals` as well as adding the data to the krusader config file that already exists at `~/xdg/config/krusaderrc` but the defaults still remain.
Sorry I couldn't help

**Comment by techie2000** [comment]
I tried changing the `/etc/xdg/openbox/environment` file to have a value of `LANG=en_GB.UTF8` with no joy :(

I'm thinking that adding language packs in the docker container, and then selecting Help/Switch Application language might at least get my dates in local (UK in my case) rather than US format - currently there are no alternative options on that menu

**Comment by techie2000** [comment]
Not sure if [https://github.com/gliderlabs/docker-alpine/issues/144#issuecomment-339906345](https://github.com/gliderlabs/docker-alpine/issues/144#issuecomment-339906345) would help?

Perhaps override the KDE language configuration, e.g. `KDE_LANG=en kprogram &` starts a program with English 'translation' if the necessary files are installed? (idea from [https://www.linuxtopia.org/online_books/linux_desktop_guides/kde_desktop_user_guide/environment-variables.html](https://www.linuxtopia.org/online_books/linux_desktop_guides/kde_desktop_user_guide/environment-variables.html))

**Comment by djaydev** [comment]
Honestly I'm clueless on how any of that works. 
You can try to test any changes in the container by running `docker exec -it krusader sh` "krusader" is the name of the container you are using.  From there you'll get a command prompt from inside the container.
